// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwdqsqgmcaoewnusdlqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZHFzcWdtY2FvZXdudXNkbHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzczMjksImV4cCI6MjA3MDE1MzMyOX0.RoGNDprN55s6-KBBefOSdNIIYi_GmPSh3zwgYKg_CAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});